spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          backend: secret
          default-key: application
          profile-separator: "-"
          kv-version: 2
          authentication: TOKEN
          token: hvs.xxxxxxxxxxxxxxxxx
        native:
          search-locations: classpath:/configurations
server:
  port: 8888